@startuml
skinparam sequenceArrowThickness 2
skinparam roundcorner 20
skinparam maxmessagesize 60
skinparam sequenceParticipant underline

actor User
participant "Browser" as A
participant "Request" as B
participant "Background Processing" as C
participant "ClusterStateCache" as D

activate D

User -> A: Select Cluster
activate A

A -> B: "/api/instance_summaries_with_tasks"
activate B

B -> C: Get State
activate C
C -> D: Create
activate D
C -> D: INITIAL
C --> B: INITIAL

B --> A: INITIAL
deactivate B

C -> D: FETCHING

A -> B: "/api/instance_summaries_with_tasks"
activate B
B -> C: Get State
C --> B: FETCHING
B --> A: FETCHING
deactivate B

C -> D: FETCHED

A -> B: "/api/instance_summaries_with_tasks"
activate B
B -> C: Get State
C --> B: FETCHED
B --> A: FETCHED
deactivate B

D -> D : Expire
deactivate D

A --> User: Render Graph
deactivate A


deactivate C
deactivate D

@enduml